### ISSUE TITLE
"making lists unmergeable" appears to break on Python 3.2.5

### ISSUE THREAD

**Issue by thenaterhood** [pylover/pymlconf#16]
It appears the changes from 17 hours ago "making lists unmergeable" (27c34b9c6d3f52d497ed76c03499752ce51a9c5b) has a problem on Python 3.2.5. Works fine in Python 3.5.1 and 3.2.3. Broke my Travis CI build today.

The error I get is `AttributeError: 'ConfigList' object has no attribute 'clear'`. The full log is here: https://travis-ci.org/thenaterhood/heartbeat/jobs/102250279

Unfortunately I can't pinpoint what's wrong with it, otherwise I would give you a hand there.

**Comment by thenaterhood** [comment]
Sorry, looks like 3.2.3 is broken as well. Ancient versions there. I fixed my issue by requiring a specific older version. May be worth noting somewhere in your docs the Python versions you support.

**Comment by pylover** [comment]
sorry for late, ok, thanks for the issue,  i'll respond in short mater of time.

**Comment by pylover** [comment]
It's not ok with mergable lists, because of the duplicated values just like:

    color: [255, 255, 255]

any idea ?

**Comment by thenaterhood** [comment]
It looks like in older versions of Python, there isn't a list.clear() method. There is an equivalent way of doing it that doesn't make use of .clear though, which I'll put in a pull for that should work both in the older and newer versions of Python.
